### ISSUE TITLE
Ubuntu Repo is out of sync

### ISSUE THREAD

**Issue by purema4** [ClubCedille/mirrors#16]
Salut!

Est-ce possible que les packets d'Ubuntu soient non synchronisés?

Je compare les date de modifications avec ceux de l'université de waterloo, et ils ne "matchent" pas.

Laissez moi savoir, limit je pourrais résoudre le problem.

**Comment by mikefaille** [comment]
@purema4 sans trouble mec !

**Comment by mikefaille** [comment]
Fait juste paratager ta clef ssh, on te fait confiance

**Comment by purema4** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtCrKdgkOSfGI/I/ipYJVN9JM/23vWveSpHDyBfZJioLq34F9efnVY5Td586oUaOvjgxFUPj5BL1t9quJUaI3SqD1idFuYN/mh5H6DXzdgLZ9iwyNIZGSxzObvx+mgsi3X8DyzDJych3dPwGneopfYIRPAfd+pgnq4UapbFWT2g/lSOWYgXPW9IjISAYa1EdowuXEl4vD8lKXIlJd/L0JO2JOWv1u6+7ClWiMNPwYWLghGDWDS/X3+8u9RSSvvLBMVmIm7oMpj3qxhRGRe1kGTHL+7s++Vn8v03r+4gk0HscR/5ni1noGb+6feEu/9jQeqpMZbuGHpqvMId72RL9AAfT4hCXRhDfONeJz3bu7ucCy4/6BHOEROq3RrA3VFZLCfif+792N0SKg+zec7Em0tYl9MjW/2nG7FuqkIDGwMKDvOuj9VdHJHiNZ782Made9257cjE/HXZFmkKpJpqE/8J2DRb3Khx53kORuK4HbIi/Bi/Cdh4vNlhdpk0kgaiLNIg/k91iDkxWwEk7NSUIAirM21rtMmElrZ1Pa1cxUjg+hghG/dpjMPdnlhzsoU9wzGDjdVASEZQ5trVf5V3G6o4eq6OMwaovcHbDe0tPgwEbX5xkJOaBuGitgT8Es8APA0Uovl7TQK0tFMhcBkru5Xqdcbvk6pSaZ/SqucdOp4cw== PopOS


ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDC9GLeE2Xybf7NQyA38C3RYCrzYVXnhakFy1rwEAzpQH1rYoPvT2XzzLvIa75xNOXvaW+5WYYMh1BZJNsFNgFMeWj6JHtizl8yDGjtumlon85LrVpqDq7o1bDwKQCbvx9jwqqc9WjgmsJ6w79lBQy8DLP9igqvXhblze2vrV+rVi0dIzY2fUdoKylLmsuXtfXv+u3l2+I2/O+8LHn02v7/gykJvwvHR+7kRL/MoKxdEd/oVwHAfdZr0qRfMRGqzNf1BolwPRiFYJcLCV3PnOgk1wdX9fiQxcg9Dmq+yFlQv9ty+b0YDTW9DSM+vJIf8x1W1H1Hisi0H+XIy1lqAUpQCR7Uk44LRXpJ8mCTWvw0Jp3NFF99yxdAWOinth+wk1wvPlyBhZH4ntNXT3WntaUoabedE/LBHRo3CaEzjBUk2u1IG0ahlbr1dzgtR+NpPGHADshTUuxWrUUSscLw5jgUOVbdJzcU8X45jGPlAc7x1DJQSgPTaQoCTS8PUv3odAD5pRMXvqAotlQeC8ea1Pe9Rgt9uTVtpdGq+MbO2P+lkpLhORNsibqpXOxGs7Co94rHvBSwTIQjlyVQ0m3cM4jRR7EEEMlcD0jKVAR12HBE0AkkhNgiEMVNSWO6j8TYCAk5DepzIj837fhadzx8okPUU+fxViMC9pEGS7wcbTgMew== root@DESKTOP-DU8T10H

**Comment by mikefaille** [comment]
C'est fait ! Aussi, j'ai retiré tes vielles clefs. Mais, remets les en places si tu les veux vraiment.

**Comment by mikefaille** [comment]
@purema4 Quoi de neuf doc (aka directeur de campagne ) ?

**Comment by mikefaille** [comment]
elle s'est fait après aussi. Il ne faut pas juste rgader le dossier parent

**Comment by purema4** [comment]
Salut!

J'ai modifié le script afin de chercher les packets des archive d'ubuntu CA au lieu DOVH 
commit: d9842b65be2b072debbf496248ce5e666acea143

Après avoir regardé les dates de modifications, je peut voir c'est à jour d'aujourdhui et matches ceux de l'archive ubuntu:
`
drwxr-xr-x. 7 mirror mirror 12 Apr 26 19:38 bionic
drwxr-xr-x. 7 mirror mirror 12 Sep 10 17:18 bionic-backports
drwxr-xr-x. 7 mirror mirror 12 Sep 10 17:18 bionic-proposed
drwxr-xr-x. 7 mirror mirror 12 Sep 10 17:17 bionic-security
drwxr-xr-x. 7 mirror mirror 12 Sep 10 17:17 bionic-updates
`

le crontab -l de mirror:

`
##Ubuntu
51 */4 * * * cd mirrors/scripts/ && ./ubuntu_packages

49 */4 * * * cd mirrors/scripts/ && ./ubuntu_releases
`

@mikefaille je ferme l'issue!

**Comment by mikefaille** [comment]
Donc c'est le miroir  de OVH qui est scrap ?
