### ISSUE TITLE
Official Mirror ARCH

### ISSUE THREAD

**Issue by gzsierra** [ClubCedille/mirrors#2]
Go to [Bug Arch](https://bugs.archlinux.org) and create a feature-request (category: mirrors) containing the following information:
* Mirror domain name
* Geographical location of the mirror (country)
* URLs for supported access methods (http(s), [rsync](https://wiki.archlinux.org/index.php/Rsync)) (no ftp)
* Your mirror's available bandwidth
* An administrative contact email
* An alternative administrative contact email (optional)
* (tier 1 mirrors) Rsync IPs so your server(s) can be allowed to sync off tier 0 (rsync.archlinux.org)
* (tier 2 mirrors) The name of tier 1 mirror you are syncing from. You can find available tier 1 mirrors [here](https://www.archlinux.org/mirrors/) (sort using the tier column)

**Comment by gzsierra** [comment]
You can follow the [request here](https://bugs.archlinux.org/task/49964)

**Comment by gzsierra** [comment]
ACCEPTED

**Comment by maximest-pierre** [comment]
🐕
