### ISSUE TITLE
Request: MX Linux

### ISSUE THREAD

**Issue by aledie** [ClubCedille/mirrors#20]
Would it be possible to add MX Linux, a midweight user-friendly Debian/Antix based distro (no. 4 on distrowatch). How to mirror: 
https://mxlinux.org/wiki/rsync-server/mirroring-mxantix-linux

**Comment by anticapitalista** [comment]
As the dev of antiX Linux, I second the request.

**Comment by notarock** [comment]
We are currently syncing MX-Linux on our server at [http://mirror.cedille.club/mx-linux](http://mirror.cedille.club/mx-linux) for the first time. We expect the first sync to be over by tomorrow :)

Then, we will have to make sure that our cronjob are set up correctly before going official.
I will test our mirror in a MX-Linux VM to make sure updates are stables.

**Comment by notarock** [comment]
Good news, updates seems to work fine!
We are now hosting mx-packages at http://mirror.cedille.club/mx-linux/ 

Now, what should I do to make this mirror official?

**Comment by aledie** [comment]
P.S. Your mx-linux mirror have been already listed by antiX team here: https://antixlinux.com/antix-packages/

mx-isos will be also added here once it is created:
https://antixlinux.com/download/
