### ISSUE TITLE
Official Mirror UBUNTU

### ISSUE THREAD

**Issue by gzsierra** [ClubCedille/mirrors#5]
Please go and register it at [Launchpad](https://launchpad.net/ubuntu/+newmirror). You may need to create a Launchpad account first. When your registration is successful and approved, it will show up on the mirror lists on Launchpad. It will also be checked by Launchpad. If you registered a CD-mirror and registration is successful and approved, it will also show up on the [Ubuntu download pages](http://www.ubuntu.com/getubuntu/download).

**Comment by gzsierra** [comment]
Waiting for acceptation.

**Comment by gzsierra** [comment]
ACCEPTED

**Comment by maximest-pierre** [comment]
🐕
